name: update

on:
  push:
    branches:
      - master
    paths:
      - '00 - Prerequisites/Dockerfile'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: '00 - Prerequisites/'
          file: '00 - Prerequisites/Dockerfile'
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-nginx:latest

      - uses: sigstore/cosign-installer@main
      
      - name: Sign the images
        run: |
          cosign sign ${{ secrets.DOCKERHUB_USERNAME }}/my-nginx:latest
